# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a519dbd6ce06d434be25610ed51f0bbaad5400dbf120669d8568c34553decc2c5515908b47031eb471b233baf5677ecfc5412df9567cac3c8650a22dadae1fb

test:
  secret_key_base: 545db7411326f09a507b15d82494bfd26cbc64fd0c35b913683950ba534138c28ec44c7b85f9ecee74a97c33e0d3deb97728be4fae4f1f7837b23b3a39803def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
